version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root 
    networks:
      - server-proxy-network
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes: 
      - jenkins_home:/var/jenkins_home
  cloud-config:
    container_name: cloud-config
    image: aistated/net.pannenko.cicd.cloud-config
    ports:
      - "8888:8888"
    volumes:
      - ~/.ssh:/root/.ssh aistated/net.pannenko.cicd.cloud-config
  client-proxy:
    container_name: client-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - client-proxy-network
  server-proxy:
    container_name: server-proxy
    image: jwilder/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - server-proxy-network
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    restart: always
    ports:
      - "8081:8081"
    user: "root:root"
    volumes:
      - ./artifactory/access:/var/opt/jfrog/artifactory/access
      - ./artifactory/backup:/var/opt/jfrog/artifactory/backup
      - ./artifactory/data:/var/opt/jfrog/artifactory/data
      - ./artifactory/etc/plugins:/var/opt/jfrog/artifactory/etc/plugins
      - ./artifactory/logs:/var/opt/jfrog/artifactory/logs
      - ./artifactory/etc/security/master.key:/var/opt/jfrog/artifactory/etc/security/master.key  
volumes:
  jenkins_home:
networks:
  server-proxy-network:
  client-proxy-network:

#docker run -e VIRTUAL_HOST=test.localhost --name US1234 --network ops_server-proxy-network aistated/net.pannenko.cicd.server1
#docker run -e VIRTUAL_HOST=test.localhost --name US1234 --network ops_client-proxy-network aistated/net.pannenko.cicd.client1